name: Generate Latest JSON

on:
  release:
    types:
      - published

jobs:
  generate-latest-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate latest.json
        run: |
          echo '{"version": "2.0.0"}' > latest.json

      - name: Upload latest.json to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./latest.json
          asset_name: latest.json
          asset_content_type: application/json